### ISSUE TITLE
DateFormatterWithFormat is not thread safe

### ISSUE THREAD

**Issue by aramark-pivotal** [Azure/azure-storage-ios#74] opened 2017-12-14 16:40 UTC
When attempting to retrieve blob attributes we encounter an occasional application crash pointing to `[df setLocale:[[NSLocale alloc] initWithLocaleIdentifier:AZSCPosix]];` can this be synchronized?

`+(NSDateFormatter *) dateFormatterWithFormat:(NSString *)format
{
    static NSDateFormatter *df = nil;
    if (!df) {
        df = [[NSDateFormatter alloc] init];
        [df setLocale:[[NSLocale alloc] initWithLocaleIdentifier:AZSCPosix]];
        [df setCalendar: [[NSCalendar alloc] initWithCalendarIdentifier:AZSGregorianCalendar]];
        [df setTimeZone:[NSTimeZone timeZoneWithName:AZSCUtc]];
    }
    
    NSDateFormatter *dateFormat = [df copy];
    [dateFormat setDateFormat:format];
    return dateFormat;
}`

**Comment by mannie** [comment] 2018-01-19 04:10
Might I propose referring to this thread for a solution, please: https://github.com/Azure/azure-storage-ios/issues/67#issuecomment-358861466

**Comment by jayMcBee** [comment] 2018-01-21 11:00
Same here - crashes the app in 

+ [AZSUtil dateFormatterWithFormat:] 

so azure-storage-ios is effectively not usable on all Apple platforms as of today!

**Comment by zezha-msft** [comment] 2018-01-22 20:17
Duplicate of #67

**Closed by zezha-msft** 2018-01-22 20:17 UTC
