### ISSUE TITLE
Support Table Operation in IOS

### ISSUE THREAD

**Issue by girishghoda** [Azure/azure-storage-ios#41] opened 2016-09-08 06:54 UTC
Hi Azure Team,

Like android support table related operation ,why not in IOS?
When you add table support operation in IOS?

Thank you

**Comment by rambo-msft** [comment] 2016-09-19 21:34
Hi @girishghoda, table support is still in the works, and is being actively developed. Stay tuned!

**Comment by zezha-msft** [comment] 2017-04-04 00:58
Closing this issue since it is a duplicate of this [other issue](https://github.com/Azure/azure-storage-ios/issues/16)

**Closed by zezha-msft** 2017-04-04 00:58 UTC
