### ISSUE TITLE
Xcode 8, swift 3- redefinition of module 'asl'

### ISSUE THREAD

**Issue by Ruthberg** [Azure/azure-storage-ios#42] opened 2016-09-08 09:03 UTC
Hi, I have been using AZSClient for a while, but got into a shitstorm of errors when using xcode 8 and swift 3. And once again it seems that asl is at the centre of the issue. Reproduce by simply downloading xcode 8 gm and start a new project, then import AZSClient through cocoapods.

**Comment by natemann** [comment] 2016-09-14 16:54
I am having the same issue. Any Update?

**Comment by Ruthberg** [comment] 2016-09-15 06:09
I tried to use legacy code with xcode 8, but still had the same problem. It seems I won't be able to upgrade to xcode 8 until this is resolved. I did consider converting parts of the library to Swift, but there is a lot of dependencies.

**Comment by natemann** [comment] 2016-09-15 14:10
are you using cocoapods or building framework manually? I am using cocoapods, am going to try to build framework manually.

**Comment by Ruthberg** [comment] 2016-09-16 05:27
I'm using cocoapods. For a while I built it manually, but this had it's own drawback with signing, bitcode and the need to rebuild with every new version of xcode.

**Comment by AFcgi** [comment] 2016-09-18 09:49
Is there any pull request to fix it? I need Swift 3 too.

**Comment by Ruthberg** [comment] 2016-09-19 11:17
Have not had time to test this, but maybe this article could help?
http://www.aerisweather.com/blog/playing-nicely-together-swift-dependencies-and-cocoapods/
If anyone tries this, please let me know how that worked out.

**Comment by asorrin-msft** [comment] 2016-09-20 22:32
So it looks like the problem is that Xcode 8 / Swift 3 / iOS 10+ now includes the asl library, so all the extra stuff we're doing in the CocoaPod to include asl.h is no longer necessary (like it was in prior versions.)  

I'm looking into how to have the configuration behave differently depending on XCode version, but here's a temporary workaround.  (Take a backup of your project first, just in case - I've briefly tested this, but no guarantees.)  Go to the build settings for your target.  Filter for the "Import Paths" setting.  You should see a path like $(SRCROOT)/Pods/AZSClient/asl/* (possibly other paths as well, it depends on what else you're using in your project.)  Just delete the AZSClient reference, and that should fix the redefinition problem.

I'll update this thread when we ship a cocoapod that behaves properly on the latest versions of XCode/Swift/iOS

**Comment by togonow** [comment] 2016-09-25 19:03
I have the same issue with xcode 7.3 
![screen shot 2016-09-25 at 12 02 58 pm](https://cloud.githubusercontent.com/assets/4708158/18817558/16490856-8318-11e6-8dae-baa79639ff87.png)

**Comment by togonow** [comment] 2016-09-25 19:06
just a dirty fix, commenting this file fixed the issue:
`/*
 module asl [system] [extern_c] {
    header "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/asl.h"
    export *
}
 */
`

**Comment by mikeRozen** [comment] 2016-10-21 11:32
Same issue. **togonow** Suggestion  helped.

**Comment by lehn0058** [comment] 2016-11-17 22:18
Same issue here. @togonow suggestion helped me as well.

**Comment by waterskier2007** [comment] 2017-03-30 02:41
Still no update on this?

**Comment by zezha-msft** [comment] 2017-04-04 00:29
@waterskier2007 I apologize for the lack of update these last months. I assure you that we are committed to solve this problem and make the library better in general. I will update you once this problem is fixed.

**Comment by SrdjanSpasojevic** [comment] 2017-04-13 12:42
@togonow You suggestion helped, comment those lines for iPhone and iPhone simulator and it works.

**Comment by zezha-msft** [comment] 2017-05-08 09:41
This problem should now be solved with the latest version 0.2.3. Please let us know if you still encounter any problem.

I apologize for the late fix, I assure you that we are committed to make this library better and will update it significantly more frequently from now on.

**Closed by zezha-msft** 2017-05-08 09:41 UTC
Labels: bug

**Comment by HideCode7** [comment] 2017-05-12 16:44
I tried to add this in my project but i have the same error "Redefinition of module ´asl´"

**Comment by waterskier2007** [comment] 2017-05-12 16:45
@HideCode7 make sure you run pod update instead of pod install to update your local repo

**Comment by HideCode7** [comment] 2017-05-12 16:56
@waterskier2007 , i tried "pod update" but i have the same error :s

**Comment by waterskier2007** [comment] 2017-05-12 17:16
@HideCode7 what does the line look like in your pod file? Are you specifying a specific version or is it a floating reference?

**Comment by HideCode7** [comment] 2017-05-12 17:18
@waterskier2007 I resolved my problem, i have the Framework Search paths incorrect. Thanks for the help

**Comment by waterskier2007** [comment] 2017-05-12 17:19
@HideCode7 cool :)

**Comment by zezha-msft** [comment] 2017-05-13 00:51
@HideCode7  Glad you solved it!

@waterskier2007 Thanks for helping out! 👍

**Comment by gerlandiolucena** [comment] 2017-05-17 12:42
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'AZSClient'
            file_iphoneos = 'Pods/AZSClient/asl/iphoneos/module.modulemap'
            file_iphonesimulator = 'Pods/AZSClient/asl/iphonesimulator/module.modulemap'
            file_macosx = 'Pods/AZSClient/asl/macosx/module.modulemap'
            
            list_files = [file_iphoneos, file_iphonesimulator, file_macosx]
            list_files.each do |file_name|
                puts "Reading #{file_name}"
                text = File.read(file_name)
                new_contents = ""
                File.open(file_name, "w") {|file| file.puts new_contents }
            end
            
            puts "Changed and writing #{file_name} because of incompatibility with Swift 3 and Xcode SDK"
        end
    end
end

**Comment by zezha-msft** [comment] 2017-05-17 17:49
@gerlandiolucena Thanks for sharing your solution!

This problem should now be fixed in the latest version 0.2.4. You could do a "pod update" to get it. 😃
